name: Basic

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force'
        required: true
        type: choice
        options: [yes, no]

jobs:
  Basic:
    name: Basic
    runs-on: ubuntu-latest

    steps:
      - name: List users
        run: getent passwd

      - name: List groups
        run: getent group

      - name: List /etc
        run: ls -lah /etc
