name: RunnerInfo

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force'
        required: true
        type: choice
        options: [yes, no]

jobs:
  Ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Current user info
        run: id
    
      - name: List users
        run: getent passwd

      - name: List groups
        run: getent group

      - name: Print environment variables
        run: printenv

      - name: List /etc
        run: ls -lah /etc/

  macOS:
    name: macOS
    runs-on: macos-latest

    steps:
      - name: Current user info
        run: id
    
      - name: List users
        run: dscl . list /Users

      - name: List groups
        run: dscl . list /Groups
        
      - name: Print environment variables
        run: printenv

      - name: List /etc
        run: ls -lah /etc/
