name: Basic

on:
  push:
    branches: [master]

jobs:
  Basic:
    name: Basic
    runs-on: ubuntu-latest

    steps:
      - name: List users
        run: getent passwd

      - name: List groups
        run: getent group

      - name: List /etc
        run: ls -lah /etc
