name: RunnerInfo

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force'
        required: true
        type: choice
        options: [yes, no]

jobs:
  Ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: List users
        run: |
          echo "::group::List users"
          getent passwd
          echo "::endgroup::"

      - name: List groups
        run: |
          printf "%s\n" "::group::List groups"
          getent group
          echo "::endgroup::"

      - name: List directories
        run: |
          # \033[34mtest\033[0m
          echo -e "::group::\e[34mList /etc\e[0m"
          ls -lah /etc/
          echo "::endgroup::"
          echo -e "::group::\e[34mList home\e[0m"
          ls -lah $HOME
          echo "::endgroup::"

  macOS:
    name: macOS
    runs-on: macos-latest

    steps:
      - name: List users
        run: dscl . list /Users

      - name: List groups
        run: dscl . list /Groups

      - name: List /etc
        run: ls -lah /etc/
