name: CreateRepo

on:
  push:
    branches: [master]

env:
  REPOSITORY: rpm-software-management/createrepo_c
  VERSION: 0.15.11

jobs:
  CreateRepoC:
    name: CreateRepoC
    runs-on: ubuntu-latest

    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt install -y libcurl4-openssl-dev \
                              libbz2-dev libxml2-dev \
                              libssl-dev zlib1g-dev \
                              pkg-config \
                              libglib2.0-dev \
                              liblzma-dev \
                              libsqlite0-dev \
                              libsqlite3-dev \
                              librpm-dev \
                              libzstd-dev \
                              python3.9-dev \
                              cmake

      - name: Build createrepo_c binary
        run: |
          git clone --depth=1 --branch=${{env.VERSION}} \
                    https://github.com/${{env.REPOSITORY}}.git createrepo_c

          cd createrepo_c
          mkdir build
          cd build
          
          cmake .. -DWITH_ZCHUNK=NO -DWITH_LIBMODULEMD=NO
          make -j 1

          mkdir -p ~/.cache

          cp src/createrepo_c ~/.cache/
