name: CreateRepo

on:
  push:
    branches: [master]

env:
  CR_REPO: rpm-software-management/createrepo_c
  CR_VERSION: 0.15.11

jobs:
  CreateRepoBuild:
    name: CreateRepoBuild
    runs-on: ubuntu-latest

    steps:
      - name: Cache createrepo_c binary
        uses: actions/cache@v3
        id: createrepo-bin-cache
        with:
          path: ~/.cache/bin/createrepo_c
          key: ${{runner.os}}-ek-rep-createrepoc-${{env.CR_VERSION}}

      - name: Install build dependencies
        if: steps.createrepo-bin-cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt install -y libcurl4-openssl-dev \
                              libbz2-dev libxml2-dev \
                              libssl-dev zlib1g-dev \
                              pkg-config \
                              libglib2.0-dev \
                              liblzma-dev \
                              libsqlite0-dev \
                              libsqlite3-dev \
                              librpm-dev \
                              libzstd-dev \
                              python3.9-dev \
                              cmake

      - name: Build createrepo_c binary
        if: steps.createrepo-bin-cache.outputs.cache-hit != 'true'
        run: |
          git clone --depth=1 --branch="${{env.CR_VERSION}}" \
                    "https://github.com/${{env.CR_REPO}}.git" createrepo_c

          cd createrepo_c
          mkdir build
          cd build
          
          cmake .. -DWITH_ZCHUNK=NO -DWITH_LIBMODULEMD=NO -DENABLE_DRPM=OFF
          make -j 1

          mkdir -p ~/.cache/bin/

          cp src/createrepo_c "$HOME/.cache/bin/"

      - name: Update PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Print createrepo_c version info
        run: createrepo_c --version
